"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    "nav.home": "BERANDA",
    "nav.track": "PERIKSA PESANAN",
    "status.online": "ONLINE",
    "home.welcome": "SELAMAT DATANG DI GEMARTOPUP",
    "home.subtitle1": "PUSAT LAYANAN TOP-UP GAME & VOUCHER INSTAN 24/7. HARGA YANG LEBIH KOMPETITIF,",
    "home.subtitle2": "100% AMAN DAN TERPERCAYA. TRANSAKSI MUDAH DENGAN PILIHAN PEMBAYARAN LENGKAP.",
    "home.market": "DAFTAR LAYANAN",
    "home.popular": "PALING BANYAK DICARI",
    "home.live": "STATUS REALTIME",
    "home.status": "STATUS",
    "home.active": "AKTIF",
    "home.maintenance": "GANGGUAN",
    "cat.all": "SEMUA LAYANAN",
    "cat.game": "GAME",
    "cat.voucher": "VOUCHER",
    "cat.pulsa": "PULSA & TOKEN",
    
    "order.return": "< KEMBALI KE AWAL",
    "order.target": "ID PENGGUNA",
    "order.sysready": "SISTEM AKTIF",
    "order.step1": "01. MASUKKAN DATA PENGGUNA",
    "order.userid": "ID PENGGUNA",
    "order.zoneid": "ID ZONA",
    "order.check": "CEK NICKNAME",
    "order.found": "AKUN DITEMUKAN:",
    "order.step2": "02. PILIH PAKET",
    "order.step3": "03. PILIH PEMBAYARAN",
    "order.summary": "RINGKASAN PESANAN",
    "order.item": "BARANG",
    "order.price": "HARGA",
    "order.fee": "BIAYA ADMIN",
    "order.total": "TOTAL",
    "order.execute": "EKSEKUSI PESANAN",
    "order.alert": "MOHON ISI SEMUA DATA YANG DIBUTUHKAN",
    "order.alert_check": "MOHON CEK NICKNAME TERLEBIH DAHULU",
    "badge.bestseller": "TERLARIS",
    "badge.promo": "PROMO",
    
    "track.title": "PERIKSA PESANAN",
    "track.desc": "MASUKKAN ID INVOICE ANDA DI BAWAH UNTUK MEMERIKSA STATUS PESANAN SECARA REAL-TIME.",
    "track.invoice": "ID INVOICE",
    "track.button": "EKSEKUSI PENCARIAN",
    "track.alert": "MOHON MASUKKAN ID INVOICE YANG VALID",
    
    "inv.title": "INVOICE TRANSAKSI",
    "inv.invoiceid": "ID INVOICE",
    "inv.time": "WAKTU",
    "inv.target": "TARGET ID",
    "inv.package": "PAKET",
    "inv.paymethod": "METODE PEMBAYARAN",
    "inv.price": "HARGA ITEM",
    "inv.fee": "BIAYA ADMIN",
    "inv.amount": "TOTAL TAGIHAN",
    "inv.window": "BATAS WAKTU PEMBAYARAN",
    "inv.scan": "SCAN UNTUK MEMBAYAR",
    "inv.sim": "SIMULASIKAN PEMBAYARAN",
    "inv.received": "PEMBAYARAN DITERIMA",
    "inv.processing": "TRANSAKSI SEDANG DIPROSES OLEH SISTEM...",
    "inv.home": "KEMBALI KE BERANDA",
    "inv.expired": "TRANSAKSI KADALUARSA",
    "inv.expired.desc": "BATAS WAKTU PEMBAYARAN TELAH HABIS. SILAKAN BUAT PESANAN BARU.",
    "inv.new": "BUAT PESANAN BARU",
    "inv.download": "UNDUH INVOICE",
    "inv.wa": "KIRIM KE WHATSAPP",
    "inv.cs": "BANTUAN CS",
    
    "status.awaiting": "MENUNGGU PEMBAYARAN",
    "status.process": "SEDANG DIPROSES",
    "status.pending": "TERTUNDA (PENDING)",
    "status.success": "TERKIRIM (SUKSES)",
    "status.failed": "BATAL (GAGAL)",
    "status.exp": "KADALUARSA",
    
    "footer.desc": "Seller top up game, voucher, pulsa, token pln dengan harga merakyat, aman dan terpercaya. 100% LEGAL Dengan Layanan 24/7 Non stop dan transaksi lebih mudah dengan berbagai pilihan pembayaran lengkap.",
    "footer.help": "Butuh Bantuan",
    "footer.nav": "NAVIGASI",
    "footer.fast": "AKSES CEPAT",
    "footer.terms": "KETENTUAN",
    "footer.support": "Dukungan Pelanggan",
    "footer.faq": "FAQ",
    "footer.tos": "Syarat & Ketentuan Layanan",
    "footer.privacy": "Kebijakan Privasi",
    "footer.follow": "IKUTI KAMI",
    "footer.registered": "TERDAFTAR DI",
    "footer.rights": "GEMARTOPUP TERMINAL V1.0",
    "footer.secure": "KONEKSI AMAN TERBENTUK",

    "support.title": "DUKUNGAN PELANGGAN",
    "support.desc": "Tim kami siap membantu Anda. Hubungi kami melalui salah satu channel di bawah ini.",
    "support.wa_desc": "Respon cepat, tersedia 24/7",
    "support.email_desc": "Untuk pertanyaan umum & kerjasama",
    "support.ig_desc": "Info promo & update terbaru",
    "support.hours_title": "JAM OPERASIONAL",
    "support.hours_desc": "Layanan kami beroperasi 24 jam non-stop, 7 hari seminggu. Namun pada jam 00:00 - 08:00 WIB, respon mungkin sedikit lebih lambat karena keterbatasan operator.",
    "support.response_title": "ESTIMASI WAKTU RESPON",
    "support.response_desc": "Kami berusaha merespon setiap pesan dalam waktu maksimal 15 menit pada jam aktif (08:00 - 00:00 WIB). Untuk pertanyaan yang memerlukan investigasi lebih lanjut, waktu penyelesaian adalah 1x24 jam.",
    "support.complaint_title": "PROSEDUR PENGADUAN",
    "support.complaint_1": "Hubungi admin melalui WhatsApp dengan menyertakan ID Invoice.",
    "support.complaint_2": "Sertakan bukti transfer (screenshot) jika terkait masalah pembayaran.",
    "support.complaint_3": "Jelaskan kronologi masalah secara singkat dan jelas.",
    "support.complaint_4": "Tim kami akan merespon dan menyelesaikan keluhan Anda sesegera mungkin.",

    "faq.title": "FREQUENTLY ASKED QUESTIONS",
    "faq.desc": "Temukan jawaban dari pertanyaan yang paling sering diajukan oleh pelanggan kami.",
    "faq.more_title": "MASIH ADA PERTANYAAN?",
    "faq.more_desc": "Jika pertanyaan Anda belum terjawab, silakan hubungi kami langsung melalui",

    "terms.title": "SYARAT & KETENTUAN LAYANAN",
    "terms.desc": "Dengan menggunakan layanan Gemartopup, Anda dianggap telah membaca, memahami, dan menyetujui seluruh syarat dan ketentuan berikut.",
    "terms.s1_title": "KETENTUAN UMUM",
    "terms.s1_p1": "Gemartopup adalah platform penyedia layanan top-up game, voucher digital, pulsa, dan token PLN secara online. Layanan ini dioperasikan secara independen oleh Gemartopup.",
    "terms.s1_p2": "Dengan mengakses atau menggunakan layanan kami, Anda menyatakan bahwa Anda berusia minimal 13 tahun dan memiliki kapasitas hukum untuk menyetujui ketentuan ini.",
    "terms.s2_title": "LAYANAN & TRANSAKSI",
    "terms.s2_l1": "Semua harga yang tertera sudah termasuk biaya layanan kecuali disebutkan lain (biaya admin ditampilkan terpisah).",
    "terms.s2_l2": "Pelanggan wajib memastikan kebenaran data yang diinput (User ID, Zone ID, nomor tujuan) sebelum melakukan konfirmasi pesanan.",
    "terms.s2_l3": "Pesanan yang sudah dikonfirmasi dan dibayar tidak dapat dibatalkan.",
    "terms.s2_l4": "Proses top-up dilakukan setelah pembayaran dikonfirmasi oleh admin melalui WhatsApp.",
    "terms.s3_title": "PEMBAYARAN",
    "terms.s3_p1": "Ketentuan pembayaran yang berlaku di Gemartopup:",
    "terms.s3_l1": "Pembayaran dilakukan melalui transfer bank (BRI, BCA) atau e-wallet (OVO, GoPay, DANA) sesuai nominal yang tertera di Invoice.",
    "terms.s3_l2": "Batas waktu pembayaran adalah 24 jam sejak pesanan dibuat. Pesanan yang tidak dibayar dalam batas waktu akan otomatis kadaluarsa.",
    "terms.s3_l3": "Transfer harus sesuai nominal. Kelebihan transfer akan dikembalikan, kekurangan transfer harus dilunasi sebelum pesanan diproses.",
    "terms.s4_title": "PEMBATALAN & PENGEMBALIAN DANA",
    "terms.s4_p1": "Kebijakan pembatalan dan pengembalian dana:",
    "terms.s4_l1": "Pengembalian dana (refund) hanya diberikan jika terjadi kesalahan dari pihak Gemartopup (misalnya top-up gagal masuk padahal data sudah benar).",
    "terms.s4_l2": "Kesalahan input data oleh pelanggan (salah ID, salah nominal) bukan tanggung jawab Gemartopup, namun kami akan membantu semaksimal mungkin.",
    "terms.s4_l3": "Proses refund memakan waktu 1-3 hari kerja tergantung metode pembayaran.",
    "terms.s5_title": "LARANGAN",
    "terms.s5_p1": "Pengguna dilarang untuk:",
    "terms.s5_l1": "Menggunakan layanan untuk tujuan ilegal, penipuan, atau merugikan pihak lain.",
    "terms.s5_l2": "Melakukan penyalahgunaan sistem, termasuk penggunaan bot atau script otomatis.",
    "terms.s5_l3": "Menyebarkan informasi palsu terkait layanan Gemartopup.",
    "terms.s6_title": "BATASAN TANGGUNG JAWAB",
    "terms.s6_p1": "Gemartopup tidak bertanggung jawab atas kerugian yang timbul akibat gangguan server pihak ketiga (server game, sistem pembayaran), force majeure, atau kesalahan input data oleh pelanggan. Kami akan berusaha semaksimal mungkin untuk menyelesaikan setiap masalah yang terjadi.",
    "terms.s7_title": "PERUBAHAN KETENTUAN",
    "terms.s7_p1": "Gemartopup berhak mengubah, menambah, atau menghapus bagian dari Syarat & Ketentuan ini kapan saja tanpa pemberitahuan sebelumnya. Penggunaan layanan setelah perubahan dianggap sebagai persetujuan atas ketentuan yang telah diperbarui.",
    "terms.updated": "Terakhir diperbarui: Juli 2026",

    "privacy.title": "KEBIJAKAN PRIVASI",
    "privacy.desc": "Gemartopup berkomitmen untuk melindungi privasi dan keamanan data pribadi Anda. Kebijakan ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi informasi Anda.",
    "privacy.s1_title": "INFORMASI YANG KAMI KUMPULKAN",
    "privacy.s1_p1": "Kami mengumpulkan informasi berikut saat Anda menggunakan layanan kami:",
    "privacy.s1_l1": "Data transaksi: User ID game, Zone ID, nominal pembelian, metode pembayaran, dan waktu transaksi.",
    "privacy.s1_l2": "Data kontak: Nomor WhatsApp yang digunakan untuk konfirmasi pembayaran.",
    "privacy.s1_l3": "Data teknis: Alamat IP, jenis browser, dan perangkat yang digunakan untuk mengakses layanan kami.",
    "privacy.s1_l4": "Data Invoice: Riwayat pesanan dan status transaksi yang tersimpan di sistem kami.",
    "privacy.s2_title": "PENGGUNAAN INFORMASI",
    "privacy.s2_p1": "Informasi yang kami kumpulkan digunakan untuk:",
    "privacy.s2_l1": "Memproses dan mengirimkan pesanan top-up Anda.",
    "privacy.s2_l2": "Menghubungi Anda terkait status pesanan atau konfirmasi pembayaran.",
    "privacy.s2_l3": "Meningkatkan kualitas layanan dan pengalaman pengguna.",
    "privacy.s2_l4": "Mencegah penipuan dan penyalahgunaan layanan.",
    "privacy.s3_title": "PENYIMPANAN DATA",
    "privacy.s3_p1": "Data transaksi Anda disimpan di server cloud yang aman (Supabase) dengan enkripsi. Kami menyimpan data transaksi untuk keperluan rekam jejak dan penyelesaian sengketa. Data tidak akan disimpan lebih lama dari yang diperlukan.",
    "privacy.s4_title": "PEMBAGIAN DATA KE PIHAK KETIGA",
    "privacy.s4_p1": "Kami tidak menjual, memperdagangkan, atau menyewakan data pribadi Anda kepada pihak ketiga. Data hanya dibagikan kepada:",
    "privacy.s4_l1": "Penyedia layanan pembayaran (bank, e-wallet) untuk memproses transaksi Anda.",
    "privacy.s4_l2": "Pihak berwenang jika diwajibkan oleh hukum yang berlaku di Indonesia.",
    "privacy.s5_title": "KEAMANAN DATA",
    "privacy.s5_p1": "Kami menerapkan langkah-langkah keamanan teknis untuk melindungi data Anda, termasuk enkripsi data, akses server yang terbatas, dan pemantauan sistem secara berkala. Meskipun demikian, tidak ada sistem yang 100% aman, dan kami tidak dapat menjamin keamanan absolut.",
    "privacy.s6_title": "HAK PENGGUNA",
    "privacy.s6_p1": "Sebagai pengguna, Anda memiliki hak untuk:",
    "privacy.s6_l1": "Meminta akses ke data pribadi Anda yang kami simpan.",
    "privacy.s6_l2": "Meminta penghapusan data pribadi Anda (dengan catatan bahwa data transaksi tertentu mungkin tetap disimpan untuk keperluan hukum).",
    "privacy.s6_l3": "Menghubungi kami untuk pertanyaan terkait privasi melalui WhatsApp atau Email.",
    "privacy.s7_title": "PERUBAHAN KEBIJAKAN",
    "privacy.s7_p1": "Kebijakan Privasi ini dapat diperbarui sewaktu-waktu. Perubahan akan berlaku segera setelah dipublikasikan di halaman ini. Penggunaan layanan setelah perubahan dianggap sebagai persetujuan atas kebijakan yang telah diperbarui.",
    "privacy.updated": "Terakhir diperbarui: Juli 2026"
  },
  en: {
    "nav.home": "HOME",
    "nav.track": "CHECK ORDER",
    "status.online": "ONLINE",
    "home.welcome": "WELCOME TO GEMARTOPUP",
    "home.subtitle1": "24/7 INSTANT GAME TOP-UP & VOUCHER CENTER. HIGHLY COMPETITIVE PRICES,",
    "home.subtitle2": "100% SAFE AND TRUSTED. EASY TRANSACTIONS WITH COMPLETE PAYMENT OPTIONS.",
    "home.market": "SERVICE LIST",
    "home.popular": "MOST SEARCHED",
    "home.live": "REALTIME STATUS",
    "home.status": "STATUS",
    "home.active": "ACTIVE",
    "home.maintenance": "MAINTENANCE",
    "cat.all": "ALL SERVICES",
    "cat.game": "GAME",
    "cat.voucher": "VOUCHER",
    "cat.pulsa": "CREDIT & TOKEN",
    
    "order.return": "< BACK TO START",
    "order.target": "SERVICE",
    "order.sysready": "SYSTEM ACTIVE",
    "order.step1": "01. INPUT USER DATA",
    "order.userid": "USER ID",
    "order.zoneid": "ZONE ID",
    "order.check": "CHECK ID",
    "order.found": "ACCOUNT FOUND:",
    "order.step2": "02. SELECT PACKAGE",
    "order.step3": "03. SELECT PAYMENT",
    "order.summary": "ORDER SUMMARY",
    "order.item": "ITEM",
    "order.price": "PRICE",
    "order.fee": "FEE",
    "order.total": "TOTAL",
    "order.execute": "EXECUTE ORDER",
    "order.alert": "PLEASE FILL ALL REQUIRED FIELDS",
    "order.alert_check": "PLEASE CHECK ID FIRST",
    "badge.bestseller": "BESTSELLER",
    "badge.promo": "PROMO",
    
    "track.title": "CHECK ORDER",
    "track.desc": "ENTER YOUR INVOICE ID BELOW TO CHECK THE STATUS OF YOUR ORDER IN REAL-TIME.",
    "track.invoice": "INVOICE ID",
    "track.button": "EXECUTE QUERY",
    "track.alert": "PLEASE ENTER A VALID INVOICE ID",
    
    "inv.title": "TRANSACTION INVOICE",
    "inv.invoiceid": "INVOICE ID",
    "inv.time": "TIMESTAMP",
    "inv.target": "TARGET ID",
    "inv.package": "PACKAGE",
    "inv.paymethod": "PAYMENT METHOD",
    "inv.price": "ITEM PRICE",
    "inv.fee": "ADMIN FEE",
    "inv.amount": "TOTAL DUE",
    "inv.window": "PAYMENT WINDOW",
    "inv.scan": "SCAN TO PAY",
    "inv.sim": "SIMULATE PAYMENT",
    "inv.received": "PAYMENT RECEIVED",
    "inv.processing": "TRANSACTION IS BEING PROCESSED BY THE SYSTEM...",
    "inv.home": "RETURN TO HOME",
    "inv.expired": "TRANSACTION EXPIRED",
    "inv.expired.desc": "THE PAYMENT WINDOW HAS LAPSED. PLEASE CREATE A NEW ORDER.",
    "inv.new": "CREATE NEW ORDER",
    "inv.download": "DOWNLOAD INVOICE",
    "inv.wa": "SEND TO WHATSAPP",
    "inv.cs": "CS SUPPORT",
    
    "status.awaiting": "AWAITING PAYMENT",
    "status.process": "PROCESSING",
    "status.pending": "PENDING",
    "status.success": "DELIVERED (SUCCESS)",
    "status.failed": "FAILED (CANCELED)",
    "status.exp": "EXPIRED",
    
    "footer.desc": "Game top-up seller, vouchers, credit, PLN tokens at affordable prices, safe and trusted. 100% LEGAL with 24/7 non-stop service and easier transactions with various complete payment options.",
    "footer.help": "Need Help",
    "footer.nav": "NAVIGATION",
    "footer.fast": "QUICK ACCESS",
    "footer.terms": "TERMS",
    "footer.support": "Customer Support",
    "footer.faq": "FAQ",
    "footer.tos": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.follow": "FOLLOW US",
    "footer.registered": "REGISTERED AT",
    "footer.rights": "GEMARTOPUP TERMINAL V1.0",
    "footer.secure": "SECURE CONNECTION ESTABLISHED",

    "support.title": "CUSTOMER SUPPORT",
    "support.desc": "Our team is ready to help you. Reach us through any of the channels below.",
    "support.wa_desc": "Fast response, available 24/7",
    "support.email_desc": "For general inquiries & partnerships",
    "support.ig_desc": "Latest promos & updates",
    "support.hours_title": "OPERATING HOURS",
    "support.hours_desc": "Our service operates 24 hours non-stop, 7 days a week. However, between 00:00 - 08:00 WIB (GMT+7), response times may be slightly slower due to limited operators.",
    "support.response_title": "ESTIMATED RESPONSE TIME",
    "support.response_desc": "We strive to respond to every message within a maximum of 15 minutes during active hours (08:00 - 00:00 WIB). For inquiries requiring further investigation, resolution time is within 24 hours.",
    "support.complaint_title": "COMPLAINT PROCEDURE",
    "support.complaint_1": "Contact admin via WhatsApp with your Invoice ID.",
    "support.complaint_2": "Attach transfer proof (screenshot) if related to payment issues.",
    "support.complaint_3": "Explain the issue briefly and clearly.",
    "support.complaint_4": "Our team will respond and resolve your complaint as soon as possible.",

    "faq.title": "FREQUENTLY ASKED QUESTIONS",
    "faq.desc": "Find answers to the most commonly asked questions by our customers.",
    "faq.more_title": "STILL HAVE QUESTIONS?",
    "faq.more_desc": "If your question hasn't been answered, feel free to contact us directly via",

    "terms.title": "TERMS OF SERVICE",
    "terms.desc": "By using Gemartopup services, you are deemed to have read, understood, and agreed to all the following terms and conditions.",
    "terms.s1_title": "GENERAL TERMS",
    "terms.s1_p1": "Gemartopup is an online platform providing game top-up, digital voucher, phone credit, and PLN token services. This service is independently operated by Gemartopup.",
    "terms.s1_p2": "By accessing or using our services, you confirm that you are at least 13 years old and have the legal capacity to agree to these terms.",
    "terms.s2_title": "SERVICES & TRANSACTIONS",
    "terms.s2_l1": "All listed prices include service fees unless stated otherwise (admin fees are displayed separately).",
    "terms.s2_l2": "Customers must ensure the accuracy of input data (User ID, Zone ID, destination number) before confirming the order.",
    "terms.s2_l3": "Orders that have been confirmed and paid cannot be canceled.",
    "terms.s2_l4": "Top-up processing begins after payment is confirmed by admin via WhatsApp.",
    "terms.s3_title": "PAYMENT",
    "terms.s3_p1": "Payment terms applicable at Gemartopup:",
    "terms.s3_l1": "Payment is made via bank transfer (BRI, BCA) or e-wallet (OVO, GoPay, DANA) according to the amount shown on the Invoice.",
    "terms.s3_l2": "Payment deadline is 24 hours from order creation. Unpaid orders will automatically expire.",
    "terms.s3_l3": "Transfer must match the exact amount. Overpayment will be refunded, underpayment must be settled before order processing.",
    "terms.s4_title": "CANCELLATION & REFUND",
    "terms.s4_p1": "Cancellation and refund policy:",
    "terms.s4_l1": "Refunds are only provided if there is an error on Gemartopup's side (e.g., failed top-up despite correct data).",
    "terms.s4_l2": "Data input errors by customers (wrong ID, wrong amount) are not Gemartopup's responsibility, but we will help as much as possible.",
    "terms.s4_l3": "Refund process takes 1-3 business days depending on the payment method.",
    "terms.s5_title": "PROHIBITED ACTIVITIES",
    "terms.s5_p1": "Users are prohibited from:",
    "terms.s5_l1": "Using the service for illegal purposes, fraud, or harming others.",
    "terms.s5_l2": "Abusing the system, including the use of bots or automated scripts.",
    "terms.s5_l3": "Spreading false information regarding Gemartopup services.",
    "terms.s6_title": "LIMITATION OF LIABILITY",
    "terms.s6_p1": "Gemartopup is not liable for losses arising from third-party server disruptions (game servers, payment systems), force majeure, or customer data input errors. We will do our best to resolve every issue that occurs.",
    "terms.s7_title": "CHANGES TO TERMS",
    "terms.s7_p1": "Gemartopup reserves the right to modify, add, or remove parts of these Terms & Conditions at any time without prior notice. Use of the service after changes constitutes acceptance of the updated terms.",
    "terms.updated": "Last updated: July 2026",

    "privacy.title": "PRIVACY POLICY",
    "privacy.desc": "Gemartopup is committed to protecting the privacy and security of your personal data. This policy explains how we collect, use, and protect your information.",
    "privacy.s1_title": "INFORMATION WE COLLECT",
    "privacy.s1_p1": "We collect the following information when you use our services:",
    "privacy.s1_l1": "Transaction data: Game User ID, Zone ID, purchase amount, payment method, and transaction time.",
    "privacy.s1_l2": "Contact data: WhatsApp number used for payment confirmation.",
    "privacy.s1_l3": "Technical data: IP address, browser type, and device used to access our services.",
    "privacy.s1_l4": "Invoice data: Order history and transaction status stored in our system.",
    "privacy.s2_title": "USE OF INFORMATION",
    "privacy.s2_p1": "The information we collect is used to:",
    "privacy.s2_l1": "Process and deliver your top-up orders.",
    "privacy.s2_l2": "Contact you regarding order status or payment confirmation.",
    "privacy.s2_l3": "Improve service quality and user experience.",
    "privacy.s2_l4": "Prevent fraud and service abuse.",
    "privacy.s3_title": "DATA STORAGE",
    "privacy.s3_p1": "Your transaction data is stored on secure cloud servers (Supabase) with encryption. We store transaction data for record-keeping and dispute resolution purposes. Data will not be stored longer than necessary.",
    "privacy.s4_title": "THIRD-PARTY DATA SHARING",
    "privacy.s4_p1": "We do not sell, trade, or rent your personal data to third parties. Data is only shared with:",
    "privacy.s4_l1": "Payment service providers (banks, e-wallets) to process your transactions.",
    "privacy.s4_l2": "Authorities if required by applicable Indonesian law.",
    "privacy.s5_title": "DATA SECURITY",
    "privacy.s5_p1": "We implement technical security measures to protect your data, including data encryption, restricted server access, and regular system monitoring. However, no system is 100% secure, and we cannot guarantee absolute security.",
    "privacy.s6_title": "USER RIGHTS",
    "privacy.s6_p1": "As a user, you have the right to:",
    "privacy.s6_l1": "Request access to your personal data stored by us.",
    "privacy.s6_l2": "Request deletion of your personal data (note that certain transaction data may be retained for legal purposes).",
    "privacy.s6_l3": "Contact us for privacy-related questions via WhatsApp or Email.",
    "privacy.s7_title": "POLICY CHANGES",
    "privacy.s7_p1": "This Privacy Policy may be updated at any time. Changes will take effect immediately upon publication on this page. Use of the service after changes constitutes acceptance of the updated policy.",
    "privacy.updated": "Last updated: July 2026"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("id");

  useEffect(() => {
    const saved = localStorage.getItem("gemartopup_lang") as Language;
    if (saved === "en" || saved === "id") setLang(saved);
  }, []);

  const changeLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("gemartopup_lang", newLang);
  };

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
